[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["canvas", "svg", "advanced"] }
futures = "0.3"
crossterm = "0.27.0"
engine = { path = "../engine" }

[[bin]]
name = "gui"
path = "src/main.rs"
